apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deployment
  labels:
    app: test
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      name: myapp-pod
      labels:
        app: nginx-test-env
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      app: nginx-test-env