apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
    tier: frontend
  name: nginx-test-service
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx-test-env
  type: NodePort

